project 'YAMAudioDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YAMAudioDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YAMAudioDemo

  pod 'SocketRocket'

  
  target 'YAMAudioDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YAMAudioDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
